name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        conda info
        conda list
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        git checkout main
        git status
        python setup.py build_ext -j 2
        python -m pip install -e . --no-build-isolation --no-use-pep517 --no-index
        conda list pandas
      shell: bash -el {0}
