from typing import Callable, Any, Optional

def __getattr__(name) -> Any: ...
class cache_readonly:
    def __init__(self, func: Callable[[Any], Any]) -> None: ...
    def __get__(self, obj: Any, type: Optional[type] = ...) -> Any: ...
