name: Bisect Regressions

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      good:
        description: 'good commit'
        default: 'v1.0.5'
        required: true
      bad:
        description: 'bad commit'
        default: 'HEAD'
        required: true
      code_sample:
        description: 'code sample'
        default: "import numpy as np\nimport pandas as pd\nprint(pd.__version__)"
        required: true

jobs:
  bisect:
    runs-on: ubuntu-latest
    steps:
    - name: Update for build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get clean
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas
      uses: actions/checkout@v2
    - name: Update conda environment
      run: |
        conda env update -n pandas-dev --file=environment.yml
        conda list
